### ISSUE TITLE
Get RTL-SDR parsing SAME

### ISSUE THREAD

**Issue by ke4roh** [ke4roh/RPiNWR#27]

**Comment by ke4roh** [comment]
http://www.nws.noaa.gov/directives/sym/pd01017012curr.pdf

1) The data rate is 520.83 bits per second.
2) Logic zero is 1562.5 Hz.
3) Logic one is 2083.3 Hz.
4) Mark and space bit periods are equal at 1.92 milliseconds. 

The coded message is transmitted, using Frequency Shift Keying (FSK), in the NWR audio channel. In this application and the implementation currently used by the FCC EAS, it is more accurate to refer to the code format as Audio Frequency Shift Keying (AFSK). It is transmitted at no less than 80% modulation (± 4.0 kHz deviation minimum, ± 5.0 kHz deviation maximum).

The coded message and voice message is transmitted over the NWR transmitter network using standard pre-emphasis for narrow band VHF Frequency Modulation (FM) of 6 dB per octave increasing slope from 300 Hz to 3,000 Hz applied to the modulator.

**Comment by ke4roh** [comment]
Underway.  by awalls on freenode #gnuradio -
http://lists.gnu.org/archive/html/discuss-gnuradio/2016-11/msg00047.html

**Comment by ke4roh** [comment]
<awalls1> ke4roh__: https://filebin.net/mqdehv6tjp4xxxv1
<awalls1> YOu'll want to use the File Meta Source block to play it back through the flowgraph
<awalls1> it's about 1.5 minutes of NWR RF I/Q at 250 ksps, centered at 162.487500 MHz
<awalls1> There's the ~50 second RWT in that file.
<awalls1> On WX2 at 162.400 MHz

**Comment by ke4roh** [comment]
I captured an RWT from my office using "rtl_sdr -f 162450000 wng706-201611161105".  I have yet to get gnuradio to work with my laptop[1], and I haven't tried on the RPi yet.  SNR is not best, but when I listened a few minutes prior to capturing the test, I was able to make out the audio.  Hopefully it's good enough to decode the messages.   The RWT is near the end of this file[2] which spans a few minutes.  

[1] https://github.com/ke4roh/RPiNWR/issues/26
[2] https://www.dropbox.com/s/ri5vc89lynqt9pq/wng706-201611161105?dl=0

**Comment by ke4roh** [comment]
See https://github.com/awalls-cx18/gr-nwr

**Comment by awalls-cx18** [comment]
I finally added a SAME Burst Decoder block to the gr-nwr module and nwr_fg.grc flowgraph.

It generates 4 GNURadio PDUs or messages for each SAME burst:
- printable ASCII of the burst as a GNURadio message carrying a pmt::symbol (string) type
- bytes of the burst as a GNURadio PDU with NULL metadata and a u8 vector of the bytes
- hard bits of the burst as a GNURadio PDU with NULL metadata and a u8 vector of the hard bits
- softs bits of the burst as a GNURadio PDU with NULL metadata and a f32 vector of the soft bits

The flowgraph will print out the ASCII and a hexdump of the SAME bytes to the terminal.
Printing the soft bits and hard bits dumps would have been an ugly scrolling mess on the terminal, so I didn't have it do that.
